[package]
name = "al-syntax"
version.workspace = true
edition.workspace = true

[dependencies]
al-parser = { path = "../al-parser" }
tree-sitter.workspace = true
lsp-types.workspace = true
ropey.workspace = true
tracing.workspace = true
